export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"


export const ADD_Facility = "ADD_Facility"

export const GET_FACILITY = "GET_FACILITY"

export const DELETE_FACILITY = "DELETE_FACILITY"


export const EDIT_FACILITY = "EDIT_FACILITY"

export const LOADING_FACILITY = "LOADING_FACILITY"