export const TOGGLE_THEME = "TOGGLE_THEME"




export const ADD_CONTACT = "ADD_CONTACT"

export const GET_CONTACT = "GET_CONTACT"

export const DELETE_CONTACT = "DELETE_CONTACT"

export const EDIT_CONTACT = "EDIT_CONTACT"

export const LOADING_CONTACT = "LOADING_CONTACT"

export const ERROR_CONTACT = "ERROR_CONTACT"





